on:
  push:
    branches:
      - main
name: Release

permissions:
  id-token: write  # Required for OIDC
  
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: indexing-service-client
      - name: Checkout
        uses: actions/checkout@v5
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
        if: ${{ steps.release.outputs.release_created }}
      - name: Install Dependencies
        run: pnpm install
        if: ${{ steps.release.outputs.release_created }}
      - name: Build
        run: pnpm build
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish to npm
        run: pnpm publish --access=public
        if: ${{ steps.release.outputs.release_created }}
        